image_in = checkerboard(10);
cornerDetector = vision.CornerDetector('MetricMatrixOutputPort',true);
[~,metric] = step(cornerDetector,image_in);
figure;
subplot(1,2,1);
imshow(image_in);
title('Original');
subplot(1,2,2);
imshow(imadjust(metric));
title('Corner metric');